### ISSUE TITLE
Website template/theme isn't loading

### ISSUE THREAD

**Issue by IceCereal** [MEC-Enigma/MEC-Enigma.github.io#1]
The website template isn't loading. It's very old-ish and static looking. I've inserted an image to show you what I mean. I think migrating from Hugo to the current theme might be messing something up.
![screenshot from 2018-10-09 00-05-55](https://user-images.githubusercontent.com/35899273/46627211-61e83000-cb57-11e8-910c-c25b2ecd34a7.png)

**Comment by Rochan-A** [comment]
The local version on my machine works like a charm. Probably got something to do with github pages.

![image](https://user-images.githubusercontent.com/9353539/46646387-95eb4180-cba7-11e8-95a8-87a7e6a48645.png)

**Comment by IceCereal** [comment]
@Rochan-A. I think I found another part of the issue.

I cloned the repo and opened `index.html` on my system. It worked properly. However, the moment I click on one of the links on the NavBar, (like `blog`), the page becomes like the one in the picture above. I then closed the webpage and reopened it and it looked alright. Clicking on `home` on the NavBar again made the page static.

I have no idea what this issue could mean, but could you try to replicate it in your own environment and see if you could reproduce these results?

Thanks,
IceC
